#!/usr/bin/env python3
"""Write a minimal runtime recipe into a fixture index.

Used by the A1/A2 criteria in subos_runtime_binding_test.sh, which need an
index where `latest` is NOT the maximum entry -- the shape that made a subos
run a libc it did not declare. `latest` and "the highest version in the table"
are two different questions asked of the same table, and they only look alike
while nobody holds a version back.

That shape is not hypothetical: the published index has musl at
`latest = 1.2.5` with 1.2.6 sitting in the table.

The recipe is generated rather than hand-written because a hand-rolled
two-file index does not load at all -- the catalog answers "package index not
available", which sends the test down the FALLBACK path, so a broken harness
and a broken feature would read the same. This writes into a COPY of the real
fixture index, which the rest of the suite already loads.

Exits non-zero if the file did not end up parseable-looking, because a recipe
that silently failed to write makes the caller assert against the wrong
version and report the feature broken.
"""
import pathlib
import sys

TEMPLATE = '''-- Generated by tests/e2e/support/make_runtime_recipe.py -- do not edit.
package = {{
    name = "{name}",
    homepage = "https://example.invalid/{name}",
    description = "test runtime {name}",
    type = "package",
    xpm = {{
        linux = {{
            exports = {{
                runtime = {{
                    loader = "lib/ld-{name}-test.so.1",
                    abi    = "{abi}",
                }},
            }},
            ["latest"] = {{ ref = "{latest}" }},
{entries}        }},
    }},
}}

import("xim.libxpkg.log")
import("xim.libxpkg.system")
import("xim.libxpkg.pkginfo")

function installed()
    return false
end

function install()
    return true
end

function uninstall()
    return true
end
'''

ENTRY = ('            ["{v}"] = {{ url = '
         '"https://example.invalid/{name}-{v}.tar.gz" }},\n')


def main() -> int:
    if len(sys.argv) < 5:
        print(f"usage: {sys.argv[0]} <out.lua> <name> <abi> <latest> "
              f"[<other-version> ...]", file=sys.stderr)
        return 2
    out, name, abi, latest = (pathlib.Path(sys.argv[1]), sys.argv[2],
                              sys.argv[3], sys.argv[4])
    extras = sys.argv[5:]

    # `latest` first, then any other entry in the table (held back above it, or
    # kept below it -- both are real index shapes). Order in the table is
    # irrelevant to the engine; it is written this way so a reader of the
    # generated file can see the point of the fixture at a glance.
    versions = [latest] + [v for v in extras if v != latest]
    entries = "".join(ENTRY.format(v=v, name=name) for v in versions)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(name=name, abi=abi, latest=latest,
                                   entries=entries))

    check = out.read_text()
    for v in versions:
        if f'["{v}"]' not in check:
            print(f"{out}: version {v} did not make it into the recipe",
                  file=sys.stderr)
            return 1
    if f'ref = "{latest}"' not in check:
        print(f"{out}: latest did not take", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
