#!/usr/bin/env bash
# Open a PR against openxlings/xim-pkgindex that bumps <project> to <version>.
#
# The actual lua edit is delegated to the index repo's OWN
# `.github/scripts/version-check.py --apply --only <project>`, so this script
# stays agnostic to each package's contract:
#   - res_versioned packages (e.g. xlings): appends `["<ver>"] = "XLINGS_RES"`.
#   - url_template packages (e.g. mcpp):    downloads the artifact, computes
#     sha256, appends `["<ver>"] = { url, sha256 }`.
# and always bumps `["latest"].ref`. Existing version entries are untouched.
#
# This opens a PR only — a maintainer reviews and merges it (index git source
# is intentionally NOT on the release critical path; availability is already
# guaranteed by the xlings-res binary mirror + index artifact). On merge, the
# index repo republishes its artifact + gitee-sync picks it up.
#
# Usage: tools/bump_index.sh <project> <version>       # e.g. mcpp 0.0.82
# Auth:
#   PKGINDEX_TOKEN  (required) — write to openxlings/xim-pkgindex (clone/push/PR)
#   GITHUB_TOKEN    (optional) — GitHub API rate headroom + artifact download
#                                for url_template packages (version-check.py)
set -euo pipefail

PROJ="${1:?usage: bump_index.sh <project> <version>}"
VER="${2:?usage: bump_index.sh <project> <version>}"
INDEX_REPO="${INDEX_REPO:-openxlings/xim-pkgindex}"
# One branch per project keeps one open PR carrying the newest release.
# Retain every previous bump commit, merge main, and append the next bump.
# Conflicts and concurrent remote updates fail without rewriting history.
BRANCH="bump/${PROJ}"
TOKEN="${PKGINDEX_TOKEN:?PKGINDEX_TOKEN required (write to $INDEX_REPO)}"
export PKGINDEX_TOKEN="$TOKEN"

# Keep credentials out of remote URLs and git's failure diagnostics.
auth_git() {
  GIT_TERMINAL_PROMPT=0 git -c credential.helper= \
    -c 'credential.helper=!f() { printf "%s\n" "username=x-access-token" "password=$PKGINDEX_TOKEN"; }; f' "$@"
}

info() { echo "[bump] $*"; }
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

info "cloning $INDEX_REPO"
auth_git clone -q --single-branch --branch main "https://github.com/${INDEX_REPO}.git" "$WORK/idx"
cd "$WORK/idx"
git config user.email "ci@xlings.dev"
git config user.name  "xlings-ci"
if auth_git ls-remote --exit-code --heads origin "refs/heads/$BRANCH" > /dev/null; then
  auth_git fetch -q origin "refs/heads/$BRANCH:refs/remotes/origin/$BRANCH"
  git checkout -q -b "$BRANCH" "origin/$BRANCH"
  if ! git merge --no-edit origin/main; then
    echo "[bump] FAIL: cannot merge main into $BRANCH; resolve the branch conflict explicitly." >&2
    exit 1
  fi
else
  REMOTE_STATUS=$?
  if [[ "$REMOTE_STATUS" != 2 ]]; then
    echo "[bump] FAIL: cannot inspect remote branch $BRANCH." >&2
    exit "$REMOTE_STATUS"
  fi
  git checkout -q -b "$BRANCH" origin/main
fi

info "version-check.py --apply --only $PROJ"
python3 .github/scripts/version-check.py --workspace "$PWD" --apply --only "$PROJ" > "$WORK/report.json" || {
  echo "[bump] version-check failed:" >&2; cat "$WORK/report.json" >&2 2>/dev/null || true; exit 1;
}

current_ref() {
  grep -oE 'ref = "[^"]+"' pkgs/*/"${PROJ}".lua 2>/dev/null \
    | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true
}

if git diff --quiet; then
  # "No change" has two causes that used to be indistinguishable, and the
  # wrong one exits 0.
  #
  #   (a) the index already tracks VER          — genuinely nothing to do
  #   (b) version-check.py could not do the work — it hashes each released
  #       asset off xlings-res before writing, so if the binary mirror has
  #       not finished there is nothing to hash and it edits nothing
  #
  # (b) happened on the 2026.7.27.0 release. `latest` stayed at 0.4.69, so
  # no user could `self update`, and this script reported success.
  GOT="$(current_ref)"
  if [[ "$GOT" == "$VER" ]]; then
    info "no change — index already tracks $PROJ $VER"
    exit 0
  fi
  echo "[bump] FAIL: version-check.py changed nothing, and the index still" >&2
  echo "[bump]       tracks '${GOT:-<none>}' rather than '$VER'." >&2
  echo "[bump]       Usual cause: the xlings-res assets for $VER are not up" >&2
  echo "[bump]       yet, so there was nothing to hash. Re-run after the" >&2
  echo "[bump]       binary mirror completes." >&2
  exit 3
fi

# Sanity: the resulting latest.ref should equal the released version. A
# mismatch usually means GitHub's releases/latest hasn't caught up yet (API
# lag) or a newer release exists — warn but still open the PR.
GOT="$(current_ref)"
if [[ -n "$GOT" && "$GOT" != "$VER" ]]; then
  echo "[bump] WARN: bumped latest.ref to '$GOT' but release version is '$VER' (upstream 'latest' differs?)"
fi

git add -A
git commit -qm "bump(${PROJ}): track ${VER} as latest

Auto-generated by the ${PROJ} release pipeline (bump_index.sh).
Applied via version-check.py --apply --only ${PROJ}."

info "pushing $BRANCH (append-only)"
auth_git push -q origin "$BRANCH"

# Open or UPDATE the PR. With one branch each new commit advances the
# previous release's diff, so the PR's title and body have to
# move with it -- otherwise the branch would carry 2026.8.6.1 under a title
# saying 2026.8.5.3, and the record would disagree with the change it
# describes. That is the same defect class this pipeline exists to avoid, one
# level up.
export GH_TOKEN="$TOKEN"
PR_TITLE="bump(${PROJ}): track ${VER} as latest"
PR_BODY="Automated by the ${PROJ} release pipeline. Bumps \`pkgs/*/${PROJ}.lua\` \`latest.ref\` to \`${VER}\` and appends every released version that the index is still missing (via \`version-check.py --apply --only ${PROJ}\`).

This branch is \`${BRANCH}\`. Each release preserves its history, merges the latest \`main\`, and appends a bump with an ordinary push. The same open PR is updated to carry the newest release; after a PR is merged, the next release opens a new one on this branch. Merge conflicts and concurrent remote updates stop the job for explicit resolution.

Merge to publish into the official index — the index repo then republishes its artifact and gitee-sync mirrors the change. Binaries are already live on \`xlings-res/${PROJ}\` (GitHub + GitCode)."

# `--json state`, not a bare `gh pr view`. With one branch the same head is
# reused release after release, so `gh pr view $BRANCH` also matches the
# PREVIOUS release's MERGED pr. Editing that one and skipping `pr create`
# would leave the new commits sitting on the branch with no open PR at all --
# a bump that reports success and is never reviewed.
PR_STATE="$(gh pr view "$BRANCH" -R "$INDEX_REPO" --json state -q .state 2>/dev/null || true)"
if [[ "$PR_STATE" == "OPEN" ]]; then
  info "PR already open for $BRANCH — updating title and body to $VER"
  gh pr edit "$BRANCH" -R "$INDEX_REPO" \
    --title "$PR_TITLE" --body "$PR_BODY" \
    || info "WARN: could not update the PR's title/body; the diff is correct but the description still names an older version"
else
  # Plain `if`. (Checked rather than assumed: `[[ … ]] && info …` does NOT
  # abort under `set -e` -- an AND-list's failure is exempt. The assignment
  # form `out=$(cmd)` is the one that aborts, because that is a simple command
  # failing. Same flag, opposite answers, so it is worth knowing which is
  # which.)
  if [[ -n "$PR_STATE" ]]; then
    info "previous PR for $BRANCH is $PR_STATE — opening a new one"
  fi
  gh pr create -R "$INDEX_REPO" --base main --head "$BRANCH" \
    --title "$PR_TITLE" --body "$PR_BODY"
  info "PR opened"
fi
