#!/usr/bin/env bash
# Open a PR against openxlings/xim-pkgindex that bumps <project> to <version>.
#
# The actual lua edit is delegated to the index repo's OWN
# `.github/scripts/version-check.py --apply --only <project>`, so this script
# stays agnostic to each package's contract:
#   - res_versioned packages (e.g. xlings): appends `["<ver>"] = "XLINGS_RES"`.
#   - url_template packages (e.g. mcpp):    downloads the artifact, computes
#     sha256, appends `["<ver>"] = { url, sha256 }`.
# and always bumps `["latest"].ref`. Existing version entries are untouched.
#
# This opens a PR only — a maintainer reviews and merges it (index git source
# is intentionally NOT on the release critical path; availability is already
# guaranteed by the xlings-res binary mirror + index artifact). On merge, the
# index repo republishes its artifact + gitee-sync picks it up.
#
# Usage: tools/bump_index.sh <project> <version>       # e.g. mcpp 0.0.82
# Auth:
#   PKGINDEX_TOKEN  (required) — write to openxlings/xim-pkgindex (clone/push/PR)
#   GITHUB_TOKEN    (optional) — GitHub API rate headroom + artifact download
#                                for url_template packages (version-check.py)
set -euo pipefail

PROJ="${1:?usage: bump_index.sh <project> <version>}"
VER="${2:?usage: bump_index.sh <project> <version>}"
INDEX_REPO="${INDEX_REPO:-openxlings/xim-pkgindex}"
BRANCH="bump/${PROJ}-${VER}"
TOKEN="${PKGINDEX_TOKEN:?PKGINDEX_TOKEN required (write to $INDEX_REPO)}"

info() { echo "[bump] $*"; }
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

info "cloning $INDEX_REPO"
git clone -q --depth 20 "https://x-access-token:${TOKEN}@github.com/${INDEX_REPO}.git" "$WORK/idx"
cd "$WORK/idx"
git config user.email "ci@xlings.dev"
git config user.name  "xlings-ci"
git checkout -q -B "$BRANCH"

info "version-check.py --apply --only $PROJ"
python3 .github/scripts/version-check.py --workspace "$PWD" --apply --only "$PROJ" > "$WORK/report.json" || {
  echo "[bump] version-check failed:" >&2; cat "$WORK/report.json" >&2 2>/dev/null || true; exit 1;
}

current_ref() {
  grep -oE 'ref = "[^"]+"' pkgs/*/"${PROJ}".lua 2>/dev/null \
    | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true
}

if git diff --quiet; then
  # "No change" has two causes that used to be indistinguishable, and the
  # wrong one exits 0.
  #
  #   (a) the index already tracks VER          — genuinely nothing to do
  #   (b) version-check.py could not do the work — it hashes each released
  #       asset off xlings-res before writing, so if the binary mirror has
  #       not finished there is nothing to hash and it edits nothing
  #
  # (b) happened on the 2026.7.27.0 release. `latest` stayed at 0.4.69, so
  # no user could `self update`, and this script reported success.
  GOT="$(current_ref)"
  if [[ "$GOT" == "$VER" ]]; then
    info "no change — index already tracks $PROJ $VER"
    exit 0
  fi
  echo "[bump] FAIL: version-check.py changed nothing, and the index still" >&2
  echo "[bump]       tracks '${GOT:-<none>}' rather than '$VER'." >&2
  echo "[bump]       Usual cause: the xlings-res assets for $VER are not up" >&2
  echo "[bump]       yet, so there was nothing to hash. Re-run after the" >&2
  echo "[bump]       binary mirror completes." >&2
  exit 3
fi

# Sanity: the resulting latest.ref should equal the released version. A
# mismatch usually means GitHub's releases/latest hasn't caught up yet (API
# lag) or a newer release exists — warn but still open the PR.
GOT="$(current_ref)"
if [[ -n "$GOT" && "$GOT" != "$VER" ]]; then
  echo "[bump] WARN: bumped latest.ref to '$GOT' but release version is '$VER' (upstream 'latest' differs?)"
fi

git add -A
git commit -qm "bump(${PROJ}): track ${VER} as latest

Auto-generated by the ${PROJ} release pipeline (bump_index.sh).
Applied via version-check.py --apply --only ${PROJ}."

info "pushing $BRANCH (force — bot branch)"
git push -q -f "https://x-access-token:${TOKEN}@github.com/${INDEX_REPO}.git" "$BRANCH"

# Open PR — idempotent: a force-push updates an already-open PR in place.
export GH_TOKEN="$TOKEN"
if gh pr view "$BRANCH" -R "$INDEX_REPO" >/dev/null 2>&1; then
  info "PR already open for $BRANCH (updated by force-push)"
else
  gh pr create -R "$INDEX_REPO" --base main --head "$BRANCH" \
    --title "bump(${PROJ}): track ${VER} as latest" \
    --body "Automated by the ${PROJ} release pipeline. Bumps \`pkgs/*/${PROJ}.lua\` \`latest.ref\` to \`${VER}\` and appends the new version entry (via \`version-check.py --apply --only ${PROJ}\`).

Merge to publish into the official index — the index repo then republishes its artifact and gitee-sync mirrors the change. Binaries are already live on \`xlings-res/${PROJ}\` (GitHub + GitCode)."
  info "PR opened"
fi
