export module xlings.core;

export import xlings.core.log;
export import xlings.core.diag;
export import xlings.core.uimode;
export import xlings.core.glyph;
export import xlings.core.palette;
export import xlings.core.version_order;
export import xlings.core.utils;
export import xlings.i18n;
export import xlings.core.config;
export import xlings.core.common;
export import xlings.core.compact;
export import xlings.core.profile;
export import xlings.core.subos;
export import xlings.core.cmdprocessor;
export import xlings.core.xself;
export import xlings.core.xim;
export import xlings.core.xvm;
